-- SQL migration for Prepal service
-- Creates user profile and purchase tables

-- Profiles table is linked to Supabase auth.users
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamp with time zone default current_timestamp
);

-- Purchases table stores user payments or service purchases
create table if not exists purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  product text not null,
  amount numeric(10,2) not null,
  created_at timestamp with time zone default current_timestamp
);

-- Records table keeps metadata for uploaded exports
create table if not exists records (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  title text not null,
  path text not null,
  created_at timestamp with time zone default current_timestamp
);

-- Enable Row Level Security so users can access only their data
alter table profiles enable row level security;
alter table purchases enable row level security;
alter table records enable row level security;

-- Policies allowing users to read/update their own profile
create policy "Profiles are viewable by owners" on profiles
  for select using (auth.uid() = id);
create policy "Profiles are updatable by owners" on profiles
  for update using (auth.uid() = id);

-- Policies for purchases table
create policy "Purchases are viewable by owners" on purchases
  for select using (auth.uid() = user_id);
create policy "Purchases can be inserted by logged in users" on purchases
  for insert with check (auth.uid() = user_id);

-- Policies for records table
create policy "Records are viewable by owners" on records
  for select using (auth.uid() = user_id);
create policy "Records can be inserted by logged in users" on records
  for insert with check (auth.uid() = user_id);
